import 'package:ar_drawing_app/generated/l10n.dart';

class CategoryModel {
  final String name;
  final List<String> listImageAssets;
  final String thumbnailsAssets;

  CategoryModel(
      {required this.name,
      required this.listImageAssets,
      required this.thumbnailsAssets});
}

final listCategory = [
  CategoryModel(
      name: S.current.trending,
      listImageAssets: [
        'assets/image/trending/trending_1.png',
        'assets/image/trending/trending_2.png',
        'assets/image/trending/trending_3.png',
        'assets/image/trending/trending_4.png',
        'assets/image/trending/trending_5.png',
        'assets/image/trending/trending_6.png',
        'assets/image/trending/trending_7.png',
        'assets/image/trending/trending_8.png',
        'assets/image/trending/trending_9.png',
        'assets/image/trending/trending_10.png',
        'assets/image/trending/trending_11.png',
        'assets/image/trending/trending_12.png',
        'assets/image/trending/trending_13.png',
        'assets/image/trending/trending_14.png',
        'assets/image/trending/trending_15.png',
        'assets/image/trending/trending_16.png',
        'assets/image/trending/trending_17.png',
        'assets/image/trending/trending_18.png',
        'assets/image/trending/trending_19.png',
        'assets/image/trending/trending_20.png',
      ],
      thumbnailsAssets: 'assets/image/trending_thumbnails_img.png'),
  CategoryModel(
      name: S.current.aesthetics,
      listImageAssets: [
        'assets/image/aesthetics/aesthetics_1.png',
        'assets/image/aesthetics/aesthetics_2.png',
        'assets/image/aesthetics/aesthetics_3.png',
        'assets/image/aesthetics/aesthetics_4.png',
        'assets/image/aesthetics/aesthetics_5.png',
        'assets/image/aesthetics/aesthetics_6.png',
        'assets/image/aesthetics/aesthetics_7.png',
        'assets/image/aesthetics/aesthetics_8.png',
        'assets/image/aesthetics/aesthetics_9.png',
        'assets/image/aesthetics/aesthetics_10.png',
        'assets/image/aesthetics/aesthetics_11.png',
        'assets/image/aesthetics/aesthetics_12.png',
        'assets/image/aesthetics/aesthetics_13.png',
        'assets/image/aesthetics/aesthetics_14.png',
        'assets/image/aesthetics/aesthetics_15.png',
        'assets/image/aesthetics/aesthetics_16.png',
        'assets/image/aesthetics/aesthetics_17.png',
        'assets/image/aesthetics/aesthetics_18.png',
        'assets/image/aesthetics/aesthetics_19.png',
        'assets/image/aesthetics/aesthetics_20.png',
      ],
      thumbnailsAssets: 'assets/image/aesthetics_thumbnails_img.png'),
  CategoryModel(
      name: S.current.animals,
      listImageAssets: [
        'assets/image/animals/animals_1.png',
        'assets/image/animals/animals_2.png',
        'assets/image/animals/animals_3.png',
        'assets/image/animals/animals_4.png',
        'assets/image/animals/animals_5.png',
        'assets/image/animals/animals_6.png',
        'assets/image/animals/animals_7.png',
        'assets/image/animals/animals_8.png',
        'assets/image/animals/animals_9.png',
        'assets/image/animals/animals_10.png',
        'assets/image/animals/animals_11.png',
        'assets/image/animals/animals_12.png',
        'assets/image/animals/animals_13.png',
        'assets/image/animals/animals_14.png',
        'assets/image/animals/animals_15.png',
        'assets/image/animals/animals_16.png',
        'assets/image/animals/animals_17.png',
        'assets/image/animals/animals_18.png',
        'assets/image/animals/animals_19.png',
        'assets/image/animals/animals_20.png',
      ],
      thumbnailsAssets: 'assets/image/animals_thumbnails_img.png'),
  CategoryModel(
      name: S.current.anime,
      listImageAssets: [
        'assets/image/anime/anime_1.png',
        'assets/image/anime/anime_2.png',
        'assets/image/anime/anime_3.png',
        'assets/image/anime/anime_4.png',
        'assets/image/anime/anime_5.png',
        'assets/image/anime/anime_6.png',
        'assets/image/anime/anime_7.png',
        'assets/image/anime/anime_8.png',
        'assets/image/anime/anime_9.png',
        'assets/image/anime/anime_10.png',
        'assets/image/anime/anime_11.png',
        'assets/image/anime/anime_12.png',
        'assets/image/anime/anime_13.png',
        'assets/image/anime/anime_14.png',
        'assets/image/anime/anime_15.png',
        'assets/image/anime/anime_16.png',
        'assets/image/anime/anime_17.png',
        'assets/image/anime/anime_18.png',
        'assets/image/anime/anime_19.png',
        'assets/image/anime/anime_20.png',
      ],
      thumbnailsAssets: 'assets/image/anime_thumbnails_img.png'),
  CategoryModel(
      name: S.current.cars,
      listImageAssets: [
        'assets/image/cars/cars_1.png',
        'assets/image/cars/cars_2.png',
        'assets/image/cars/cars_3.png',
        'assets/image/cars/cars_4.png',
        'assets/image/cars/cars_5.png',
        'assets/image/cars/cars_6.png',
        'assets/image/cars/cars_7.png',
        'assets/image/cars/cars_8.png',
        'assets/image/cars/cars_9.png',
        'assets/image/cars/cars_10.png',
        'assets/image/cars/cars_11.png',
        'assets/image/cars/cars_12.png',
        'assets/image/cars/cars_13.png',
        'assets/image/cars/cars_14.png',
        'assets/image/cars/cars_15.png',
        'assets/image/cars/cars_16.png',
        'assets/image/cars/cars_17.png',
        'assets/image/cars/cars_18.png',
        'assets/image/cars/cars_19.png',
        'assets/image/cars/cars_20.png',
      ],
      thumbnailsAssets: 'assets/image/cars_thumbnails_img.png'),
  CategoryModel(
      name: S.current.for_kids,
      listImageAssets: [
        'assets/image/for_kids/for_kids_1.png',
        'assets/image/for_kids/for_kids_2.png',
        'assets/image/for_kids/for_kids_3.png',
        'assets/image/for_kids/for_kids_4.png',
        'assets/image/for_kids/for_kids_5.png',
        'assets/image/for_kids/for_kids_6.png',
        'assets/image/for_kids/for_kids_7.png',
        'assets/image/for_kids/for_kids_8.png',
        'assets/image/for_kids/for_kids_9.png',
        'assets/image/for_kids/for_kids_10.png',
        'assets/image/for_kids/for_kids_11.png',
        'assets/image/for_kids/for_kids_12.png',
        'assets/image/for_kids/for_kids_13.png',
        'assets/image/for_kids/for_kids_14.png',
        'assets/image/for_kids/for_kids_15.png',
        'assets/image/for_kids/for_kids_16.png',
        'assets/image/for_kids/for_kids_17.png',
        'assets/image/for_kids/for_kids_18.png',
        'assets/image/for_kids/for_kids_19.png',
        'assets/image/for_kids/for_kids_20.png',
      ],
      thumbnailsAssets: 'assets/image/for_kids_thumbnails_img.png'),
  CategoryModel(
      name: S.current.nature,
      listImageAssets: [
        'assets/image/nature/nature_1.png',
        'assets/image/nature/nature_2.png',
        'assets/image/nature/nature_3.png',
        'assets/image/nature/nature_4.png',
        'assets/image/nature/nature_5.png',
        'assets/image/nature/nature_6.png',
        'assets/image/nature/nature_7.png',
        'assets/image/nature/nature_8.png',
        'assets/image/nature/nature_9.png',
        'assets/image/nature/nature_10.png',
        'assets/image/nature/nature_11.png',
        'assets/image/nature/nature_12.png',
        'assets/image/nature/nature_13.png',
        'assets/image/nature/nature_14.png',
        'assets/image/nature/nature_15.png',
        'assets/image/nature/nature_16.png',
        'assets/image/nature/nature_17.png',
        'assets/image/nature/nature_18.png',
        'assets/image/nature/nature_19.png',
        'assets/image/nature/nature_20.png',
      ],
      thumbnailsAssets: 'assets/image/nature_thumbnails_img.png'),
  CategoryModel(
      name: S.current.people,
      listImageAssets: [
        'assets/image/people/people_1.png',
        'assets/image/people/people_2.png',
        'assets/image/people/people_3.png',
        'assets/image/people/people_4.png',
        'assets/image/people/people_5.png',
        'assets/image/people/people_6.png',
        'assets/image/people/people_7.png',
        'assets/image/people/people_8.png',
        'assets/image/people/people_9.png',
        'assets/image/people/people_10.png',
        'assets/image/people/people_11.png',
        'assets/image/people/people_12.png',
        'assets/image/people/people_13.png',
        'assets/image/people/people_14.png',
        'assets/image/people/people_15.png',
        'assets/image/people/people_16.png',
        'assets/image/people/people_17.png',
        'assets/image/people/people_18.png',
        'assets/image/people/people_19.png',
        'assets/image/people/people_20.png',
      ],
      thumbnailsAssets: 'assets/image/people_thumbnails_img.png'),
];

final listImageDrawingStep = [
  'assets/image/drawing_lesson/drawing_lesson_1.png',
  'assets/image/drawing_lesson/drawing_lesson_2.png',
  'assets/image/drawing_lesson/drawing_lesson_3.png',
  'assets/image/drawing_lesson/drawing_lesson_4.png',
  'assets/image/drawing_lesson/drawing_lesson_5.png',
  'assets/image/drawing_lesson/drawing_lesson_6.png',
  'assets/image/drawing_lesson/drawing_lesson_7.png',
  'assets/image/drawing_lesson/drawing_lesson_8.png',
  'assets/image/drawing_lesson/drawing_lesson_9.png',
  'assets/image/drawing_lesson/drawing_lesson_10.png',
  'assets/image/drawing_lesson/drawing_lesson_11.png',
  'assets/image/drawing_lesson/drawing_lesson_12.png',
  'assets/image/drawing_lesson/drawing_lesson_13.png',
  'assets/image/drawing_lesson/drawing_lesson_14.png',
  'assets/image/drawing_lesson/drawing_lesson_15.png',
  'assets/image/drawing_lesson/drawing_lesson_16.png',
  'assets/image/drawing_lesson/drawing_lesson_17.png',
  'assets/image/drawing_lesson/drawing_lesson_18.png',
  'assets/image/drawing_lesson/drawing_lesson_19.png',
  'assets/image/drawing_lesson/drawing_lesson_20.png',
  'assets/image/drawing_lesson/drawing_lesson_21.png',
  'assets/image/drawing_lesson/drawing_lesson_22.png',
];
